---
    local_data_path: "/mnt/c/data/"
    backup_data_path: "lapishla@datastar.psych.indianapolis.iu.edu:/research/behavior_rooms/ephys/B/"
    other_folders:
        ephys:
        anymaze:
        med_pc: "lapishla@10.0.0.1:/AUTO_med/"
    suggested_name_format: "%date%_%time%_%experiment%_rat%input{rat number}%"

